### ISSUE TITLE
2018 posts not being created

### ISSUE THREAD

**Issue by nohorbee** [Anthony-Gaudino/jekyll-multiple-languages-plugin#114]
Hi,
I've just written the first post for this year. While the _site is being generated properly, the 2018 posts are not there (not even the folder).

I tried renaming the file to 2017-12-31-title.markdown and that worked (that's why I'm inferring that the problem is with 2018 posts).

Thoughts?

**Comment by sudodoki** [comment]
I can't build any posts, disregarding whether year is 2018/2017/2012, tried that on jekyll 3.7.3 and 3.1.6

**Comment by sudodoki** [comment]
This is related to https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin/issues/18

**Comment by sudodoki** [comment]
solved via https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin/pull/51

**Comment by joshcummingsdesign** [comment]
@kurtsson Can be closed.
