### ISSUE TITLE
`site.translations` does not access yml

### ISSUE THREAD

**Issue by satzz** [Anthony-Gaudino/jekyll-multiple-languages-plugin#121]
Apparently `site.translations` behaves as if translation does not exist.
It starts to work as expected only when livereload is on and after I modify any template.

**Comment by satzz** [comment]
And I confirmed it works on my project and hosting

**Comment by mrjoshc** [comment]
Fixed by #122 @kurtsson This can now be closed.

**Comment by joshcummingsdesign** [comment]
Fixed by #122 @kurtsson This can be closed.
