### ISSUE TITLE
Fallback on translate_file does not work

### ISSUE THREAD

**Issue by schancel** [Anthony-Gaudino/jekyll-multiple-languages-plugin#123]
Fallbacks for translate_file don't work correctly:

```
Liquid Exception: Included file 'xxx/features.html' not found in /Users/xxx/xxx/_i18n/es directory in index.html
```

**Comment by joshcummingsdesign** [comment]
I had the same experience. I submitted #124 to resolve this issue. I believe that if content doesn't exist in the target language, it should fall back to the default language.
