### ISSUE TITLE
Example Site: Unable to run 'bundle exec jekyll serve'

### ISSUE THREAD

**Issue by p2635** [Anthony-Gaudino/jekyll-multiple-languages-plugin#127]
I tried to follow the readme instructions to have a go at the example site but I got this when running the command in subject.

`ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Key related_posts cannot be set in the drop.`

**Comment by joshcummingsdesign** [comment]
Hi @p2635 👋 Can you give me some more information and maybe share your _config.yml and explain a bit about how you are organizing your files?

**Comment by p2635** [comment]
Thanks for getting back to me josh, I have been procrastinating on this so I will close until I get back on it.
