### ISSUE TITLE
Not excluding assets path generated by jekyll-assets

### ISSUE THREAD

**Issue by robertwbradford** [Anthony-Gaudino/jekyll-multiple-languages-plugin#43]
I created http://stackoverflow.com/q/31325665/538400, but thought I would ask here too. I have an app that uses both this plugin and [jekyll-assets](https://github.com/jekyll-assets/jekyll-assets). I also have this in my `_config.yml`:

```
languages: ['en', 'es']
exclude_from_localizations: ['assets']
```

However, when building I end up with both `_site/assets` _and_ `_site/es/assets`. How can I get it to exclude `assets` directory from the additional localizations? 

Here is a sample app: https://github.com/robertwbradford/jekyll-assets-and-multiple-languages

**Comment by Kuzirashi** [comment]
Did you manage to find workaround?

**Comment by robertwbradford** [comment]
@Kuzirashi I don't know that I ever did and ended up going with https://github.com/middleman/middleman for that project.

**Comment by alvarotrigo** [comment]
Same issue.

**Comment by maesitos** [comment]
I just pulled a request to solve this clash in jekyll-assets: https://github.com/envygeeks/jekyll-assets/pull/603

**Comment by maesitos** [comment]
I just requested a pull into  jekyll-assets to solve this clash in: https://github.com/envygeeks/jekyll-assets/pull/603

**Comment by maesitos** [comment]
Pull request merged in  jekyll-assets. This shouldn't be a problem anymore. @kurtsson @Anthony-Gaudino this issue be set as solved.
