### ISSUE TITLE
exclude_from_localizations is not excluding `.htaccess` file

### ISSUE THREAD

**Issue by johanbove** [Anthony-Gaudino/jekyll-multiple-languages-plugin#47]
On version 1.2.9, Jekyll version 2.5.3.

I am translating my site in three languages. The ``exclude_from_localizations`` works fine for folders, *.html* and *.txt* files, except for the *.htaccess* file which is being copied to each of the language folders.

I tried excluding the file but the plugin seems to ignore it.

My configuration:

``
languages: ["default", "en" ,"de"]
exclude_from_localizations: ["js", "img", "css", "humans.txt", ".htaccess", "robots.txt"]
``

**Comment by Glennvd** [comment]
+1

**Comment by Anthony-Gaudino** [comment]
Version 1.4.0 fixes this issue.

**Comment by johanbove** [comment]
Thanks :metal: 🚀
