### ISSUE TITLE
Wording on readme

### ISSUE THREAD

**Issue by 9mm** [Anthony-Gaudino/jekyll-multiple-languages-plugin#54]
I spent a little while trying to debug this gem it kept failing. Turns out it is because `exclude_from_localizations` is required, although the readme leads one to believe it's optional:

`To avoid redundancy, it is possible to exclude files and folders ...`

I was adding things one at a time following along with the directions. Might be worth it to add that to the readme.

**Comment by Anthony-Gaudino** [comment]
Fixed on 1.4.0
