### ISSUE TITLE
exclude_from_localizations is nil

### ISSUE THREAD

**Issue by pathawks** [Anthony-Gaudino/jekyll-multiple-languages-plugin#56]
The provided example site does not build out of the box.

The plugin [requires that `exclude_from_localizations` be provided in `_config.yml`](https://github.com/screeninteraction/jekyll-multiple-languages-plugin/blob/master/lib/jekyll/multiple/languages/plugin.rb#L55). If it is not, then this line causes the build to fail.

**Comment by Anthony-Gaudino** [comment]
This was fixed on 1.4.0.
