### ISSUE TITLE
Jekyll regeneration creates wront paths

### ISSUE THREAD

**Issue by jonathandion** [Anthony-Gaudino/jekyll-multiple-languages-plugin#65]
Hi,

Every time I save after the first rendering the compiler compile my project like this ```/_site/en/en/en```.

It should be ```/_site/en```

**Comment by Anthony-Gaudino** [comment]
@jonathandion thank you for reporting this.

Definitely it's a bug during site regeneration.

**Comment by Anthony-Gaudino** [comment]
@jonathandion I updated the plugin with a fix.
Please use v 1.4.1.
